"""
Initialize-catalog helpers.

Reads local initialize JSON artifacts under:
- data/initialize/agent/<db>/<table>/<column>.json
- data/initialize/agent/<db>/<table>/TABLE_<table>.json

These files are generated by the initialize stage and can be used to populate
column type/index/sample_values and lightweight semantic_summary without
querying the database.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from utils.data_paths import DataPaths


@dataclass(frozen=True)
class ColumnInitializeMeta:
    database_name: str
    table_name: str
    column_name: str
    data_type: str = ""
    comment: str = ""
    semantic_summary: str = ""
    is_primary_key: bool = False
    foreign_key_ref: str = ""
    indexes: List[Dict[str, Any]] = None  # type: ignore[assignment]
    samples: Dict[str, Any] = None  # type: ignore[assignment]


def load_table_overview(database_name: str, table_name: str) -> Optional[Dict[str, Any]]:
    """
    Load TABLE_<table>.json if present.
    Expected keys: description, columns, rows.
    """
    db = (database_name or "").strip()
    tb = (table_name or "").strip()
    if not db or not tb:
        return None
    p = DataPaths.default().initialize_agent_database_dir(db) / tb / f"TABLE_{tb}.json"
    if not p.exists():
        return None
    try:
        with p.open("r", encoding="utf-8") as f:
            obj = json.load(f)
        if isinstance(obj, dict):
            return obj
    except Exception:
        return None
    return None


def load_column_meta(database_name: str, table_name: str, column_name: str) -> Optional[ColumnInitializeMeta]:
    db = (database_name or "").strip()
    tb = (table_name or "").strip()
    col = (column_name or "").strip()
    if not db or not tb or not col:
        return None
    p = DataPaths.default().find_column_description_path(db, tb, col)
    if not p.exists() or not p.is_file():
        return None
    try:
        with p.open("r", encoding="utf-8") as f:
            obj = json.load(f)
        if not isinstance(obj, dict):
            return None
        return ColumnInitializeMeta(
            database_name=str(obj.get("database_name") or db),
            table_name=str(obj.get("table_name") or tb),
            column_name=str(obj.get("column_name") or col),
            data_type=str(obj.get("data_type") or "").strip(),
            comment=str(obj.get("comment") or "").strip(),
            semantic_summary=str(obj.get("semantic_summary") or "").strip(),
            is_primary_key=bool(obj.get("is_primary_key") or False),
            foreign_key_ref=str(obj.get("foreign_key_ref") or "").strip(),
            indexes=list(obj.get("indexes") or []),
            samples=dict(obj.get("samples") or {}),
        )
    except Exception:
        return None


def load_table_column_metas(database_name: str, table_name: str) -> Dict[str, ColumnInitializeMeta]:
    """
    Load all column metas for one table from initialize json directory.
    Excludes TABLE_*.json / DATABASE_*.json and .bak files.
    """
    db = (database_name or "").strip()
    tb = (table_name or "").strip()
    if not db or not tb:
        return {}
    table_dir = DataPaths.default().initialize_agent_database_dir(db) / tb
    if not table_dir.exists() or not table_dir.is_dir():
        return {}
    out: Dict[str, ColumnInitializeMeta] = {}
    for p in table_dir.glob("*.json"):
        name = p.name
        if name.startswith("TABLE_") or name.startswith("DATABASE_"):
            continue
        if name.endswith(".bak") or ".bak" in name:
            continue
        col = p.stem
        meta = load_column_meta(db, tb, col)
        if meta:
            out[col] = meta
    return out


def pick_sample_values(meta: ColumnInitializeMeta, *, max_values: int = 6) -> List[Any]:
    """
    Prefer distinct_samples, fall back to random_samples.
    Returned values are strings (as stored in json).
    """
    samples = meta.samples or {}
    for key in ("distinct_samples", "random_samples"):
        items = samples.get(key)
        if isinstance(items, list) and items:
            out: List[Any] = []
            for it in items:
                if isinstance(it, dict) and "sample_value" in it:
                    out.append(it.get("sample_value"))
                elif it is not None:
                    out.append(it)
                if len(out) >= max_values:
                    break
            return out
    return []


def index_string(meta: ColumnInitializeMeta) -> str:
    if meta.is_primary_key:
        return "PRIMARY"
    indexes = meta.indexes or []
    if not isinstance(indexes, list) or not indexes:
        return ""
    unique_names: set[str] = set()
    index_names: set[str] = set()
    for idx in indexes:
        if not isinstance(idx, dict):
            continue
        name = str(idx.get("index_name") or "").strip()
        if not name:
            continue
        if str(idx.get("is_unique") or "").lower() in ("true", "1"):
            unique_names.add(name)
        else:
            index_names.add(name)
    if unique_names:
        return f"UNIQUE({sorted(unique_names)[0]})"
    if index_names:
        return f"INDEX({sorted(index_names)[0]})"
    return ""


_FK_REF_RE = re.compile(r"^(?P<table>[A-Za-z0-9_]+)\\((?P<column>[A-Za-z0-9_]+)\\)$")


def parse_foreign_key_ref(ref: str) -> Optional[Tuple[str, str]]:
    """
    Parse "factories(factory_id)" -> ("factories","factory_id").
    """
    s = (ref or "").strip()
    if not s:
        return None
    m = _FK_REF_RE.match(s)
    if not m:
        return None
    return (m.group("table"), m.group("column"))


def hydrate_column_record_from_initialize(
    record: Dict[str, Any],
    *,
    schema_name: str,
) -> Dict[str, Any]:
    """
    Fill missing fields on a schema_retrieval column record using local initialize json, if present.
    This is best-effort and never raises.
    """
    try:
        db = str(record.get("database_name") or schema_name or "").strip()
        tb = str(record.get("table_name") or "").strip()
        col = str(record.get("column_name") or "").strip()
        if not db or not tb or not col or col == "*":
            return record

        meta = load_column_meta(db, tb, col)
        if not meta:
            return record

        def _set_if_empty(key: str, value: Any) -> None:
            cur = record.get(key)
            if cur is None:
                record[key] = value
                return
            if isinstance(cur, str) and not cur.strip():
                record[key] = value
                return
            if isinstance(cur, list) and not cur:
                record[key] = value
                return
            if cur == "":
                record[key] = value

        _set_if_empty("column_type", meta.data_type)
        _set_if_empty("data_type", meta.data_type)
        _set_if_empty("column_comment", meta.comment)
        _set_if_empty("semantic_summary", meta.semantic_summary)
        _set_if_empty("sample_values", pick_sample_values(meta))
        _set_if_empty("index", index_string(meta))
        # bool fields: only set if missing
        if "is_primary_key" not in record:
            record["is_primary_key"] = meta.is_primary_key
        if meta.foreign_key_ref and not str(record.get("foreign_key_ref") or "").strip():
            record["foreign_key_ref"] = meta.foreign_key_ref
        return record
    except Exception:
        return record
